version: '3'

services:
  nginx-rtmp:
    build: .
    ports:
      - {{ .Env.NGINX_RTMP_PORT }}:1935
      - {{ .Env.NGINX_HTTPS_PORT }}:443
    environment:
      - NGINX_HTTPS_PORT
      - NGINX_RTMP_PORT
      - webSiteRootURL
    volumes:
      - ./certs:/opt/certs
    networks:
      yptlive:
networks:
  yptlive: