version: '3'

services:
  nginx-rtmp:
    build: .
    ports:
      - '${NGINX_RTMP_PORT}:1935'
      - '${NGINX_HTTPS_PORT}:443'
      - '${NGINX_HTTP_PORT}:80'
    environment:
      - NGINX_HTTPS_PORT
      - NGINX_RTMP_PORT
      - webSiteRootURL='https://demo.avideo.com/'
    volumes:
      - ./certs:/opt/certs
      - ./static:/opt/static
    networks:
      yptlive:
networks:
  yptlive:
